import { BannerTemplate } from '../types/editor';

export const BANNER_TEMPLATES: BannerTemplate[] = [
  {
    id: 'business-promo',
    title: 'Modern Business Summit',
    category: 'Business Promotion',
    description: 'Corporate annual conference announcement banner',
    design: {
      id: 'template-biz-1',
      name: 'Business Promotion Banner',
      width: 1200,
      height: 630,
      background: {
        type: 'gradient',
        color: '#0F172A',
        gradient: {
          enabled: true,
          type: 'linear',
          angle: 135,
          stops: [
            { color: '#0F172A', offset: 0 },
            { color: '#1E293B', offset: 0.6 },
            { color: '#312E81', offset: 1 },
          ],
        },
      },
      elements: [
        {
          id: 'bg-img-1',
          name: 'Workspace Photo',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
          originalWidth: 1200,
          originalHeight: 800,
          x: 550,
          y: 40,
          width: 600,
          height: 550,
          rotation: 0,
          opacity: 0.95,
          zIndex: 1,
          visible: true,
          locked: false,
          borderRadius: 24,
          borderWidth: 3,
          borderColor: '#4338CA',
          objectFit: 'cover',
          filters: {
            brightness: 100,
            contrast: 105,
            saturation: 110,
            blur: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.5)',
            blur: 25,
            offsetX: 0,
            offsetY: 10,
          },
        },
        {
          id: 'badge-1',
          name: 'Category Tag',
          type: 'badge',
          text: '🚀 ANNUAL GLOBAL SUMMIT 2026',
          badgeStyle: 'pill',
          backgroundColor: '#4F46E5',
          textColor: '#FFFFFF',
          fontSize: 14,
          fontWeight: 700,
          fontFamily: "'Inter', sans-serif",
          x: 60,
          y: 80,
          width: 270,
          height: 38,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          visible: true,
          locked: false,
        },
        {
          id: 'heading-1',
          name: 'Main Title',
          type: 'text',
          text: 'SCALE YOUR ENTERPRISE',
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 68,
          fontWeight: 800,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FFFFFF',
          textAlign: 'left',
          letterSpacing: 2,
          lineHeight: 1.05,
          x: 60,
          y: 135,
          width: 480,
          height: 150,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.4)',
            blur: 10,
            offsetX: 0,
            offsetY: 4,
          },
        },
        {
          id: 'sub-1',
          name: 'Subtitle',
          type: 'text',
          text: 'Join 5,000+ industry leaders exploring the next wave of artificial intelligence and strategic cloud infrastructure.',
          fontFamily: "'Inter', sans-serif",
          fontSize: 20,
          fontWeight: 400,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#94A3B8',
          textAlign: 'left',
          letterSpacing: 0,
          lineHeight: 1.5,
          x: 60,
          y: 300,
          width: 460,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 'btn-1',
          name: 'CTA Button',
          type: 'button',
          text: 'REGISTER EARLY ACCESS →',
          textColor: '#0F172A',
          backgroundColor: '#38BDF8',
          borderColor: '#E0F2FE',
          borderWidth: 2,
          borderRadius: 12,
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 700,
          paddingX: 30,
          paddingY: 16,
          url: 'https://example.com/register',
          x: 60,
          y: 430,
          width: 290,
          height: 56,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(56, 189, 248, 0.4)',
            blur: 18,
            offsetX: 0,
            offsetY: 6,
          },
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
  {
    id: 'restaurant-offer',
    title: 'Gourmet Burger Special',
    category: 'Restaurant Offer',
    description: 'Delicious food promotion with 40% OFF discount badge',
    design: {
      id: 'template-food-1',
      name: 'Burger Promo Banner',
      width: 1080,
      height: 1080,
      background: {
        type: 'gradient',
        color: '#1C1917',
        gradient: {
          enabled: true,
          type: 'linear',
          angle: 180,
          stops: [
            { color: '#1C1917', offset: 0 },
            { color: '#292524', offset: 0.5 },
            { color: '#451A03', offset: 1 },
          ],
        },
      },
      elements: [
        {
          id: 'food-img-1',
          name: 'Delicious Burger',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80',
          originalWidth: 1000,
          originalHeight: 800,
          x: 90,
          y: 280,
          width: 900,
          height: 550,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          visible: true,
          locked: false,
          borderRadius: 30,
          borderWidth: 4,
          borderColor: '#EA580C',
          objectFit: 'cover',
          filters: {
            brightness: 105,
            contrast: 110,
            saturation: 125,
            blur: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.6)',
            blur: 35,
            offsetX: 0,
            offsetY: 15,
          },
        },
        {
          id: 'badge-offer',
          name: 'Discount Stamp',
          type: 'shape',
          shapeType: 'circle',
          fillColor: '#EF4444',
          borderColor: '#FEE2E2',
          borderWidth: 4,
          x: 820,
          y: 220,
          width: 170,
          height: 170,
          rotation: 12,
          opacity: 1,
          zIndex: 6,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(239, 68, 68, 0.5)',
            blur: 20,
            offsetX: 0,
            offsetY: 8,
          },
        },
        {
          id: 'badge-offer-text',
          name: 'Discount Text',
          type: 'text',
          text: '40% OFF',
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 42,
          fontWeight: 900,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FFFFFF',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1,
          x: 830,
          y: 275,
          width: 150,
          height: 60,
          rotation: 12,
          opacity: 1,
          zIndex: 7,
          visible: true,
          locked: false,
        },
        {
          id: 'food-heading-1',
          name: 'Food Main Title',
          type: 'text',
          text: 'WEEKEND CRAVINGS',
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 84,
          fontWeight: 900,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#F97316',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1,
          x: 90,
          y: 70,
          width: 900,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.7)',
            blur: 12,
            offsetX: 0,
            offsetY: 6,
          },
        },
        {
          id: 'food-sub-1',
          name: 'Food Tagline',
          type: 'text',
          text: 'Smoked Angus Beef • Melted Aged Cheddar • Brioche Bun',
          fontFamily: "'Montserrat', sans-serif",
          fontSize: 22,
          fontWeight: 600,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#FEF3C7',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.4,
          x: 90,
          y: 170,
          width: 900,
          height: 40,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 'food-btn',
          name: 'Order Button',
          type: 'button',
          text: 'ORDER NOW FOR DELIVERY',
          textColor: '#FFFFFF',
          backgroundColor: '#DC2626',
          borderColor: '#F87171',
          borderWidth: 3,
          borderRadius: 40,
          fontFamily: "'Montserrat', sans-serif",
          fontSize: 24,
          fontWeight: 800,
          paddingX: 45,
          paddingY: 20,
          url: 'https://example.com/menu',
          x: 290,
          y: 900,
          width: 500,
          height: 75,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(220, 38, 38, 0.6)',
            blur: 24,
            offsetX: 0,
            offsetY: 10,
          },
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
  {
    id: 'real-estate',
    title: 'Luxury Villa Showcase',
    category: 'Real Estate',
    description: 'High-end architectural property listing banner',
    design: {
      id: 'template-re-1',
      name: 'Real Estate Banner',
      width: 1200,
      height: 630,
      background: {
        type: 'solid',
        color: '#0B0F19',
      },
      elements: [
        {
          id: 're-img-1',
          name: 'Villa Exterior',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
          originalWidth: 1200,
          originalHeight: 800,
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          visible: true,
          locked: true,
          borderRadius: 0,
          borderWidth: 0,
          borderColor: '#000000',
          objectFit: 'cover',
          filters: {
            brightness: 90,
            contrast: 105,
            saturation: 105,
            blur: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
        },
        {
          id: 're-overlay',
          name: 'Dark Contrast Overlay',
          type: 'overlay',
          overlayType: 'linear-gradient-lr',
          color1: 'rgba(11, 15, 25, 0.95)',
          color2: 'rgba(11, 15, 25, 0.2)',
          gradientStops: [
            { color: 'rgba(11, 15, 25, 0.95)', offset: 0 },
            { color: 'rgba(11, 15, 25, 0.65)', offset: 0.5 },
            { color: 'rgba(11, 15, 25, 0.1)', offset: 1 },
          ],
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          visible: true,
          locked: true,
        },
        {
          id: 're-badge',
          name: 'Prime Location Tag',
          type: 'badge',
          text: 'FEATURED RESIDENCE',
          badgeStyle: 'tag',
          backgroundColor: '#D97706',
          textColor: '#FFFFFF',
          fontSize: 13,
          fontWeight: 700,
          fontFamily: "'Inter', sans-serif",
          x: 80,
          y: 80,
          width: 180,
          height: 32,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
        },
        {
          id: 're-title',
          name: 'Villa Title',
          type: 'text',
          text: 'THE OBSIDIAN WATERFRONT ESTATE',
          fontFamily: "'Playfair Display', serif",
          fontSize: 48,
          fontWeight: 700,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#F8FAFC',
          textAlign: 'left',
          letterSpacing: 2,
          lineHeight: 1.15,
          x: 80,
          y: 130,
          width: 580,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 're-details',
          name: 'Specs & Price',
          type: 'text',
          text: '6 Bedrooms • 8 Bathrooms • Private Infinity Pool • 8,400 Sq Ft\nOffered at $6,850,000 USD',
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 400,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#CBD5E1',
          textAlign: 'left',
          letterSpacing: 0,
          lineHeight: 1.6,
          x: 80,
          y: 280,
          width: 550,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          visible: true,
          locked: false,
        },
        {
          id: 're-btn',
          name: 'Schedule Tour',
          type: 'button',
          text: 'SCHEDULE PRIVATE TOUR',
          textColor: '#0F172A',
          backgroundColor: '#F59E0B',
          borderColor: '#FDE68A',
          borderWidth: 2,
          borderRadius: 8,
          fontFamily: "'Inter', sans-serif",
          fontSize: 16,
          fontWeight: 700,
          paddingX: 28,
          paddingY: 15,
          url: 'https://example.com/tour',
          x: 80,
          y: 420,
          width: 260,
          height: 54,
          rotation: 0,
          opacity: 1,
          zIndex: 6,
          visible: true,
          locked: false,
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
  {
    id: 'mega-sale',
    title: 'Flash Sale 50% Off',
    category: 'Sale',
    description: 'High energy e-commerce retail discount campaign',
    design: {
      id: 'template-sale-1',
      name: 'Mega Sale Banner',
      width: 1200,
      height: 675,
      background: {
        type: 'gradient',
        color: '#4C0519',
        gradient: {
          enabled: true,
          type: 'linear',
          angle: 135,
          stops: [
            { color: '#881337', offset: 0 },
            { color: '#BE123C', offset: 0.5 },
            { color: '#E11D48', offset: 1 },
          ],
        },
      },
      elements: [
        {
          id: 'sale-shape-bg',
          name: 'Contrast Card',
          type: 'shape',
          shapeType: 'rounded-rectangle',
          fillColor: '#18181B',
          borderColor: '#F43F5E',
          borderWidth: 3,
          borderRadius: 24,
          x: 70,
          y: 60,
          width: 1060,
          height: 550,
          rotation: 0,
          opacity: 0.95,
          zIndex: 1,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.5)',
            blur: 30,
            offsetX: 0,
            offsetY: 10,
          },
        },
        {
          id: 'sale-badge',
          name: 'Flash Ribbon',
          type: 'badge',
          text: '⚡ LIMITED TIME ONLY • ENDS MIDNIGHT',
          badgeStyle: 'pill',
          backgroundColor: '#FACC15',
          textColor: '#000000',
          fontSize: 15,
          fontWeight: 900,
          fontFamily: "'Montserrat', sans-serif",
          x: 120,
          y: 110,
          width: 340,
          height: 40,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          visible: true,
          locked: false,
        },
        {
          id: 'sale-h1',
          name: 'Mega Sale Heading',
          type: 'text',
          text: 'MID-SEASON MEGA SALE',
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 78,
          fontWeight: 900,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FFFFFF',
          textAlign: 'left',
          letterSpacing: 2,
          lineHeight: 1,
          x: 120,
          y: 170,
          width: 580,
          height: 160,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
        },
        {
          id: 'sale-disc',
          name: 'Big Discount',
          type: 'text',
          text: 'UP TO 50% OFF',
          fontFamily: "'Oswald', sans-serif",
          fontSize: 44,
          fontWeight: 800,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FB7185',
          textAlign: 'left',
          letterSpacing: 1,
          lineHeight: 1.1,
          x: 120,
          y: 350,
          width: 450,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 'sale-btn',
          name: 'Claim Voucher',
          type: 'button',
          text: 'CLAIM VOUCHER & SHOP NOW',
          textColor: '#000000',
          backgroundColor: '#FACC15',
          borderColor: '#FEF08A',
          borderWidth: 2,
          borderRadius: 14,
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 800,
          paddingX: 32,
          paddingY: 18,
          url: 'https://example.com/sale',
          x: 120,
          y: 445,
          width: 320,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(250, 204, 21, 0.4)',
            blur: 20,
            offsetX: 0,
            offsetY: 8,
          },
        },
        {
          id: 'sale-photo',
          name: 'Shopping Photo',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
          originalWidth: 800,
          originalHeight: 800,
          x: 700,
          y: 90,
          width: 400,
          height: 480,
          rotation: 2,
          opacity: 1,
          zIndex: 6,
          visible: true,
          locked: false,
          borderRadius: 20,
          borderWidth: 4,
          borderColor: '#FB7185',
          objectFit: 'cover',
          filters: {
            brightness: 105,
            contrast: 110,
            saturation: 115,
            blur: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
  {
    id: 'youtube-tech',
    title: 'YouTube Tech Thumbnail',
    category: 'YouTube',
    description: 'High CTR 16:9 click-worthy video thumbnail with contrast typography',
    design: {
      id: 'template-yt-1',
      name: 'YouTube Tech Thumbnail',
      width: 1280,
      height: 720,
      background: {
        type: 'gradient',
        color: '#0B0F19',
        gradient: {
          enabled: true,
          type: 'linear',
          angle: 135,
          stops: [
            { color: '#090D16', offset: 0 },
            { color: '#111827', offset: 0.6 },
            { color: '#1E1B4B', offset: 1 },
          ],
        },
      },
      elements: [
        {
          id: 'yt-gadget',
          name: 'Tech Gadget',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=80',
          originalWidth: 1000,
          originalHeight: 700,
          x: 650,
          y: 80,
          width: 580,
          height: 560,
          rotation: -3,
          opacity: 1,
          zIndex: 1,
          visible: true,
          locked: false,
          borderRadius: 24,
          borderWidth: 4,
          borderColor: '#38BDF8',
          objectFit: 'cover',
          filters: {
            brightness: 110,
            contrast: 120,
            saturation: 120,
            blur: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
          shadow: {
            enabled: true,
            color: 'rgba(56, 189, 248, 0.4)',
            blur: 35,
            offsetX: 0,
            offsetY: 10,
          },
        },
        {
          id: 'yt-tag',
          name: 'Review Tag',
          type: 'badge',
          text: 'HONEST 30-DAY REVIEW',
          badgeStyle: 'pill',
          backgroundColor: '#EF4444',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 800,
          fontFamily: "'Inter', sans-serif",
          x: 70,
          y: 110,
          width: 250,
          height: 44,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          visible: true,
          locked: false,
        },
        {
          id: 'yt-title-1',
          name: 'Punchy Heading',
          type: 'text',
          text: 'DON’T BUY THIS',
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 88,
          fontWeight: 900,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FACC15',
          textAlign: 'left',
          letterSpacing: 2,
          lineHeight: 0.95,
          x: 70,
          y: 175,
          width: 550,
          height: 90,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
          shadow: {
            enabled: true,
            color: 'rgba(0,0,0,0.8)',
            blur: 15,
            offsetX: 0,
            offsetY: 6,
          },
        },
        {
          id: 'yt-title-2',
          name: 'Sub-Punch',
          type: 'text',
          text: 'UNTIL YOU WATCH THIS!',
          fontFamily: "'Oswald', sans-serif",
          fontSize: 48,
          fontWeight: 800,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FFFFFF',
          textAlign: 'left',
          letterSpacing: 1,
          lineHeight: 1.1,
          x: 70,
          y: 285,
          width: 530,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 'yt-highlight-box',
          name: 'Verdict Box',
          type: 'shape',
          shapeType: 'rounded-rectangle',
          fillColor: '#1E293B',
          borderColor: '#475569',
          borderWidth: 2,
          borderRadius: 12,
          x: 70,
          y: 390,
          width: 480,
          height: 120,
          rotation: 0,
          opacity: 0.95,
          zIndex: 5,
          visible: true,
          locked: false,
        },
        {
          id: 'yt-box-text',
          name: 'Verdict Text',
          type: 'text',
          text: '✓ Tested Battery Life: 48 Hours\n✓ Sound Stage & ANC Comparison\n⚠️ Hidden Flaw You Need To Know',
          fontFamily: "'Inter', sans-serif",
          fontSize: 16,
          fontWeight: 600,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#E2E8F0',
          textAlign: 'left',
          letterSpacing: 0,
          lineHeight: 1.6,
          x: 95,
          y: 410,
          width: 430,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 6,
          visible: true,
          locked: false,
        },
        {
          id: 'yt-watch-btn',
          name: 'Watch CTA',
          type: 'button',
          text: 'WATCH COMPARISON (4K) ▶',
          textColor: '#FFFFFF',
          backgroundColor: '#DC2626',
          borderColor: '#F87171',
          borderWidth: 2,
          borderRadius: 30,
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 800,
          paddingX: 30,
          paddingY: 16,
          url: 'https://youtube.com',
          x: 70,
          y: 550,
          width: 320,
          height: 56,
          rotation: 0,
          opacity: 1,
          zIndex: 7,
          visible: true,
          locked: false,
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
  {
    id: 'education-webinar',
    title: 'Masterclass Webinar',
    category: 'Education',
    description: 'Professional live workshop & course enrollment banner',
    design: {
      id: 'template-edu-1',
      name: 'Masterclass Webinar Banner',
      width: 1200,
      height: 630,
      background: {
        type: 'gradient',
        color: '#042F2E',
        gradient: {
          enabled: true,
          type: 'linear',
          angle: 135,
          stops: [
            { color: '#042F2E', offset: 0 },
            { color: '#115E59', offset: 0.7 },
            { color: '#0F766E', offset: 1 },
          ],
        },
      },
      elements: [
        {
          id: 'edu-badge',
          name: 'Badge Live',
          type: 'badge',
          text: '🔴 LIVE INTERACTIVE WEBINAR',
          badgeStyle: 'pill',
          backgroundColor: '#0D9488',
          textColor: '#CCFBF1',
          fontSize: 14,
          fontWeight: 700,
          fontFamily: "'Inter', sans-serif",
          x: 80,
          y: 80,
          width: 260,
          height: 38,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          visible: true,
          locked: false,
        },
        {
          id: 'edu-heading',
          name: 'Webinar Title',
          type: 'text',
          text: 'FULL-STACK CLOUD ARCHITECTURE',
          fontFamily: "'Montserrat', sans-serif",
          fontSize: 48,
          fontWeight: 800,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'uppercase',
          color: '#FFFFFF',
          textAlign: 'left',
          letterSpacing: 1,
          lineHeight: 1.15,
          x: 80,
          y: 135,
          width: 600,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          visible: true,
          locked: false,
        },
        {
          id: 'edu-desc',
          name: 'Description',
          type: 'text',
          text: 'Master serverless microservices, distributed caching, and zero-trust security patterns in a 3-hour intensive session with certified Principal Architects.',
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 400,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#CCFBF1',
          textAlign: 'left',
          letterSpacing: 0,
          lineHeight: 1.55,
          x: 80,
          y: 275,
          width: 580,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          visible: true,
          locked: false,
        },
        {
          id: 'edu-btn',
          name: 'Reserve Seat',
          type: 'button',
          text: 'RESERVE FREE SEAT →',
          textColor: '#042F2E',
          backgroundColor: '#2DD4BF',
          borderColor: '#99F6E4',
          borderWidth: 2,
          borderRadius: 12,
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 800,
          paddingX: 32,
          paddingY: 16,
          url: 'https://example.com/webinar',
          x: 80,
          y: 410,
          width: 270,
          height: 56,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          visible: true,
          locked: false,
        },
        {
          id: 'edu-card-info',
          name: 'Date Card',
          type: 'shape',
          shapeType: 'rounded-rectangle',
          fillColor: 'rgba(255, 255, 255, 0.1)',
          borderColor: 'rgba(45, 212, 191, 0.4)',
          borderWidth: 2,
          borderRadius: 20,
          x: 750,
          y: 110,
          width: 370,
          height: 410,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          visible: true,
          locked: false,
        },
        {
          id: 'edu-card-text',
          name: 'Speaker & Date',
          type: 'text',
          text: '🗓️ Thursday, Oct 24\n⏰ 6:00 PM EST / 3:00 PM PST\n\n🎓 Free Certificate Included\n💻 100% Practical Demos\n\nHosted by TechEdu Academy',
          fontFamily: "'DM Sans', sans-serif",
          fontSize: 18,
          fontWeight: 600,
          fontStyle: 'normal',
          textDecoration: 'none',
          textTransform: 'none',
          color: '#FFFFFF',
          textAlign: 'left',
          letterSpacing: 0,
          lineHeight: 1.8,
          x: 785,
          y: 160,
          width: 300,
          height: 300,
          rotation: 0,
          opacity: 1,
          zIndex: 6,
          visible: true,
          locked: false,
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  },
];
